name: Build and Publish .NET

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Find Project
        id: project
        shell: bash
        run: |
          PROJECT=$(find extracted -type f -name "*.csproj" | head -n 1)

          if [ -z "$PROJECT" ]; then
            echo "ERROR: No .csproj found!"
            exit 1
          fi

          echo "Project: $PROJECT"
          echo "project=$PROJECT" >> "$GITHUB_OUTPUT"

      - name: Restore
        run: |
          dotnet restore "${{ steps.project.outputs.project }}"

      - name: Build
        run: |
          dotnet build \
            "${{ steps.project.outputs.project }}" \
            --configuration Release \
            --no-restore

      - name: Publish
        run: |
          rm -rf publish

          dotnet publish \
            "${{ steps.project.outputs.project }}" \
            --configuration Release \
            --no-build \
            --output ./publish

      - name: Create ZIP
        run: |
          mkdir -p release

          cd publish
          zip -r ../release/Par30GamesApi-Publish.zip .
          cd ..

      - name: Upload Publish ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Par30GamesApi-Publish
          path: release/Par30GamesApi-Publish.zip
          retention-days: 30
